@startuml lister_selectionner_workspaces

hide footbox


actor "Utilisateur" as user
participant "système" as system
ref over user, system : Authentification

activate user
user -> system : clique sur le bouton "Sélectionner un workspace"
activate system
system --> user : affiche le panneau de sélection d'un workspace
user -> system : saisie le terme de recherche
system -> system : recherche les workspaces correspondants
system --> user : affiche les workspaces correspondants
user -> system : selectionne les workspaces
user -> system : clique sur le bouton "Valider"
system -> system : enregistre les workspaces sélectionnés
system --> user 
deactivate system
deactivate user
