@startuml pereferance_affichage

hide footbox


actor "Utilisateur" as user
participant "système" as system
ref over user, system : Authentification

activate user
user -> system : clique sur le bouton "dark mode"
activate system
system -> system : change le thème de l'application
system --> user : affiche le thème sombre/clair

deactivate system
deactivate user
