@startuml sequence_annuler_absence

hide footbox


actor "Utilisateur" as user
participant "manageAbsencePage" as manageAbsencePage << View >>
participant "settingsStore" as settingsStore << ViewModel >>
participant "profil" as profil << Model >>
participant "eliseRestApi" as eliseRestApi << service >>
ref over user,manageAbsencePage,eliseRestApi,profil,settingsStore : Authentification

activate user
user -> manageAbsencePage : clicker sur "Annuler absence"
activate manageAbsencePage
manageAbsencePage -> settingsStore : desActivateAbsence()
activate settingsStore
settingsStore -> eliseRestApi : :DELETE /profil/absence
activate eliseRestApi
eliseRestApi --> settingsStore
deactivate eliseRestApi
ref over user,manageAbsencePage,eliseRestApi : getProfil()
settingsStore --> manageAbsencePage 
deactivate settingsStore
manageAbsencePage --> user : affiche le message "Absence annulée"
deactivate manageAbsencePage



deactivate user
