@startuml sequence_declare_absence

hide footbox


actor "Utilisateur" as user
participant "manageAbsencePage" as manageAbsencePage << View >>
participant "DatePickerModal" as datePickerModal << View >>
participant "settingsStore" as settingsStore << ViewModel >>
participant "eliseRestApi" as eliseRestApi << service >>

ref over user,settingsStore,eliseRestApi : Authentification

activate user
user -> manageAbsencePage : clique sur le bouton "activer absence"
activate manageAbsencePage
    alt Utilisateur a choisit une date de fin
        ref over user,settingsStore,eliseRestApi : add_absence
    else Utilisateur n'a pas choisit une date de fin
        manageAbsencePage --> user : affiche le message "date de fin d'absence invalide"
        user -> manageAbsencePage : clique sur le bouton "end Date"
        manageAbsencePage --> user : affiche le modal de selection de date
        user -> datePickerModal : choisit une date de fin
        activate datePickerModal
        datePickerModal --> manageAbsencePage : affiche la date de fin
        deactivate datePickerModal
        user -> manageAbsencePage : clique sur le bouton "activer absence"
        ref over user,settingsStore,eliseRestApi : add_absence

    end
    group add_absence
    manageAbsencePage -> settingsStore : addAbsence() 
    activate settingsStore
    settingsStore -> eliseRestApi : :PUT /profile/absence
    activate eliseRestApi
    eliseRestApi --> settingsStore 
    deactivate eliseRestApi
    ref over user,settingsStore,eliseRestApi : getProfile()
    settingsStore --> manageAbsencePage 
    deactivate settingsStore
    manageAbsencePage -> user : affiche le message "absence activée"
    end




deactivate user
