@startuml sequence_visualiser_profile

hide footbox


actor "Utilisateur" as user
participant "settingsPage" as settingsPage << View >>
participant "editeProfilePage" as editeProfilePage << View >>
participant "settingsStore" as settingsStore << ViewModel >>
participant "profile" as profile << Model >>

ref over user,settingsPage,editeProfilePage,settingsStore,profile : Authentification
ref over user,settingsPage,editeProfilePage,settingsStore,profile: settings_Page
group profilePage
activate user
user -> settingsPage : clique sur le bouton "edite Profile"
activate settingsPage
settingsPage -> editeProfilePage : editProfile()
deactivate settingsPage
activate editeProfilePage
editeProfilePage -> settingsStore : profile
activate settingsStore
settingsStore -> profile : getProfile()
activate profile
profile --> settingsStore : profile
deactivate profile
settingsStore --> editeProfilePage : profile
deactivate settingsStore
editeProfilePage --> user : editeProfilePage
deactivate editeProfilePage
end
