@startuml senquence_pereferance_affichage

hide footbox


actor "Utilisateur" as user
participant "settingsPage" as settingsPage << View >>

participant "settingsStore" as settingsStore << ViewModel >>
participant "darkMode" as darkMode << Model >>

ref over user,settingsPage,settingsStore,darkMode : Authentification

activate user
user -> settingsPage : clique sur le bouton "dark mode"
activate settingsPage
settingsPage -> settingsStore : changeTheme()
activate settingsStore
alt theme clair
settingsStore -> darkMode : setDarkMode(false)
activate darkMode
darkMode --> settingsStore : lightThemeResponse
deactivate darkMode
settingsStore --> settingsPage
settingsPage --> user
else theme sombre
settingsStore -> darkMode : setDarkMode(true)
activate darkMode
darkMode --> settingsStore : darkThemeResponse
deactivate darkMode
settingsStore --> settingsPage 
deactivate settingsStore
settingsPage --> user 
deactivate settingsPage
end
deactivate user
