@startuml sequence_clear_cache

hide footbox

actor "Utilisateur" as user
participant "settingsPage" as settingsPage << View >>

participant "settingsStore" as settingsStore << ViewModel >>
participant "documentsStore" as documentsStore << ViewModel >>
participant "workspacesStore" as workspacesStore << ViewModel >>
participant "statsStore" as statsStore << ViewModel >>
participant "signatureStore" as signatureStore << ViewModel >>

ref over user,settingsPage,settingsStore,documentsStore,workspacesStore,statsStore,signatureStore : Authentification

activate user
user -> settingsPage : clique sur le bouton "vider le cache"
activate settingsPage
settingsPage --> user : affiche le panneau de confirmation
user -> settingsPage : clique sur le bouton "confirmer"
settingsPage -> settingsStore : clearCache()

activate settingsStore

settingsStore -> documentsStore : clearAllData()
activate documentsStore
documentsStore --> settingsStore
deactivate documentsStore
settingsStore -> workspacesStore : clearAllData()
activate workspacesStore
workspacesStore --> settingsStore
deactivate workspacesStore
settingsStore -> statsStore : clearAllData()
activate statsStore
statsStore --> settingsStore
deactivate statsStore
settingsStore -> signatureStore : clearAllData()
activate signatureStore
signatureStore --> settingsStore
deactivate signatureStore
settingsStore --> settingsPage
deactivate settingsStore
settingsPage --> user


deactivate user
