@startuml sequence_search_affect_delegation

hide footbox


actor "Utilisateur" as user
participant "settingsPage" as settingsPage << View >>
participant "addDelegate" as delegate << View >>
participant "settingsnStore" as settingsnStore << ViewModel >>
participant "workspaceStore" as workspaceStore << ViewModel >>
participant "profil" as profil << Model >>
participant "eliseRestApi" as eliseRestApi << service >>
participant "eliseWebService" as es << service >>
ref over user,settingsPage,profil,settingsnStore,es,workspaceStore,eliseRestApi : Authentification

activate user
user -> settingsPage : clique sur le bouton "ajouter"
activate settingsPage
settingsPage --> user : affiche le panneau d'ajout de délégation
deactivate settingsPage
user -> delegate : saisie le terme de recherche 
activate delegate
delegate -> workspaceStore : getWorkspaces()
activate workspaceStore
workspaceStore -> es : GetFlowchartItems()
activate es
es --> workspaceStore : getWorkspacesResponse
deactivate es
workspaceStore --> delegate : getWorkspacesResponse
deactivate workspaceStore
alt workspace trouvé
    delegate -> user : affiche la liste des workspaces
    user -> delegate : selectionne le workspace à déléguer
    delegate -> settingsnStore : addDelegation()
    activate settingsnStore
    settingsnStore -> eliseRestApi : :POST /delegations/create
    activate eliseRestApi
    eliseRestApi --> settingsnStore : createDelegationResponse
    deactivate eliseRestApi
    alt delegation ajoutée
        settingsnStore -> settingsnStore : getProfil()
        settingsnStore -> settingsnStore : getAbsence()
        settingsnStore -> profil : setProfil()
        activate profil
        profil --> settingsnStore : setProfilResponse
        deactivate profil
        settingsnStore --> settingsPage : createDelegationResponse
        deactivate settingsnStore
        activate settingsPage
        settingsPage --> user : affiche le message "Délégation ajoutée"
    else delegation non ajoutée
        settingsPage --> user : affiche le message "Erreur lors de l'ajout de la délégation"
        deactivate settingsPage
    end 
else workspace non trouvé
    delegate -> user : affiche le message "Aucun workspace trouvé"
    deactivate delegate

end
deactivate user
