@startuml sequence_annuler_absence

hide footbox


actor "Utilisateur" as user
participant "editeProfilePage" as editeProfilePage << View >>
participant "Camera" as camera << View >>
participant "settingsStore" as settingsStore << ViewModel >>
participant "profile" as profile << Model >>
participant "eliseRestApi" as eliseRestApi << service >>

ref over user,editeProfilePage,eliseRestApi,profile,settingsStore : Authentification

activate user
user -> editeProfilePage : clique sur le bouton "camera"
activate editeProfilePage
editeProfilePage --> user : ouvre la camera
deactivate editeProfilePage
user -> camera : prend une photo
activate camera
camera --> user : retourne la photo
user -> camera : confirme la photo
camera -> settingsStore : updateAvatar()
deactivate camera
activate settingsStore
settingsStore -> eliseRestApi : elise-avatar/update : POST
activate eliseRestApi
eliseRestApi --> settingsStore : updateResponse
deactivate eliseRestApi
alt avatar mis à jour
settingsStore -> settingsStore : setProfileAvatar()
settingsStore -> settingsStore : getProfile()
settingsStore -> profile : setProfile()
activate profile
profile -> settingsStore : getProfileResponse
deactivate profile
settingsStore -> editeProfilePage : updateAvatarResponse
activate editeProfilePage
editeProfilePage -> user : affiche le message "Avatar mis à jour"
else
settingsStore -> editeProfilePage : updateAvatarResponse
deactivate settingsStore
editeProfilePage -> user : affiche le message "Erreur lors de la mise à jour de l'avatar"
deactivate editeProfilePage
end
deactivate user
 