@startuml sequence_view_signature

hide footbox


actor "Utilisateur" as user
participant "ListeSignature" as liste << View >>
participant "VisualiserSignature" as view << View >>
participant "ListeSignature" as vm << ViewModel >>
participant "Signature" as model << Model >>
participant "EliseWebService" as ws << Service >>


ref over user,liste,view,vm,model,ws : Authentification
activate user
user -> liste : ClickVisualiserSignature()
activate liste
liste -> view : afficher fenêtre de confirmation
deactivate liste
activate view
user -> view : ClickFermer()
view -> user : cache l'interface de visualisation
view -> liste : afficher ListeSignature
deactivate view
activate liste
liste -> user : affiche la liste des signatures
deactivate liste
deactivate user