@startuml sequence_view_signature

hide footbox


actor "Utilisateur" as user
participant "System" as system << Controller >>
participant "ListeSignature" as liste << View >>
participant "ViewSignature" as view << View >>
participant "ListeSignature" as vm << ViewModel >>
participant "Signature" as model << Model >>
participant "EliseWebService" as ws << Service >>


ref over user, system : Authentification
activate user
user -> liste : ClickViewSignature()
activate liste
liste -> view : afficher fenêtre de confirmation
deactivate liste
activate view
view -> user : affiche la fenêtre de confirmation
user -> view : Choisit l'action
alt Oui
    view -> vm : ViewSignature()
    activate vm
    vm -> ws : ViewSignature()
    activate ws
    ws -> vm : ViewSignature
    deactivate ws
    vm -> model : ViewSignature()
    activate model
    model -> vm : ViewSignature
    deactivate model
    vm -> view : ViewSignature
    deactivate vm
    alt Succès
        view -> user : affiche message de succès
    else Echec
        view -> user : affiche message d'erreur
    end
else Non
    view -> user : AnnulerViewSignature()
end
view -> user : cache l'interface de suppression
view -> liste : afficher ListeSignature
deactivate view
activate liste
liste -> user : affiche la liste des signatures
deactivate liste
deactivate user