@startuml sequence_create_signature

hide footbox


actor "Utilisateur" as user
participant "SignaturesPage" as liste << View >>
participant "CreateSignature" as create << View >>
participant "SignaturesStore" as vm << ViewModel >>
participant "Signature" as model << Model >>
participant "EliseWebService" as ws << Service >>



ref over user, liste,create,vm,model,ws : Authentification
activate user
user -> liste : CliqueCreerSignature()
activate liste
alt Utilisateur a dessiné une signature
liste -> create : affiche l'interface de création de signature
deactivate liste
activate create
create --> user
user -> create : CliqueValider()
alt Utilisateur a entré un nom de signature
create -> vm : AddSignature()
activate vm
vm -> ws : UploadFile()
activate ws
ws -> vm : UploadFileResponse
deactivate ws
vm -> ws : AddPersonnalSignature()
activate ws
ws -> vm : AddPersonnalSignatureResponse
deactivate ws
vm -> model : AjouterSignature()
activate model
model --> vm 
deactivate model
vm --> create 
deactivate vm
alt signature enregistrée

create -> user : affiche un message de succès
else Erreur lors de l'enregistrement de la signature
create -> user : affiche un message d'erreur
end
else Utilisateur n'a pas entré de nom de signature
create -> user : affiche un message d'erreur
end
else Utilisateur n'a pas dessiné de signature
create -> user : affiche un message d'erreur
end
create -> user : cache l'interface de création de signature
create -> liste : afficher ListeSignature
deactivate create
activate liste
liste -> vm : GetSignatureList()
activate vm
vm -> ws : GetPersonnalSignatureList()
activate ws
ws -> vm : GetPersonnalSignatureListResponse
deactivate ws
vm -> model : RecupererListeSignature()
activate model
model -> vm : ChargerListeSignature
deactivate model
vm --> liste 
deactivate vm
liste -> user : affiche la liste des signatures
deactivate liste
deactivate user