@startuml sequence_view_signature

hide footbox


actor "Utilisateur" as user
participant "SignaturesPage" as liste << View >>
participant "ViewSignature" as view << View >>
participant "SignaturesStore" as vm << ViewModel >>
participant "Signature" as model << Model >>


ref over user,liste,view,vm,model,ws : Authentification
activate user
user -> liste : CliqueVisualiserSignature()
activate liste
liste -> view : afficher le panneau de visualisation
deactivate liste
activate view
view -> vm : GetSignatureById()
activate vm
vm -> model : GetSignatureById()
activate model
model --> vm
deactivate model
vm --> view 
deactivate vm
view -> user : affiche la signature
user -> view : CliqueFermer()
view -> user : cache le panneau de visualisation
view -> liste : afficher ListeSignature
deactivate view
activate liste
liste -> user : affiche la liste des signatures
deactivate liste
deactivate user