@startuml delete_notification

hide footbox


actor "Utilisateur" as user
participant "système" as system


ref over user, system : Authentification
activate user
user -> system : glisse la notification vers la gauche
activate system
system --> user : notification supprimée
deactivate system
deactivate user