@startuml sequence_activate_notification

hide footbox


actor "Utilisateur" as user
participant "EditProfilePage" as edit << View >>
' participant "NotificationStore" as notif << ViewModel >>
participant "PushNotification" as push << System >>
participant "FirebaseCloudMessaging" as firebase << System >>
participant "NotificationServer" as server << Service >>



ref over user, edit, push, firebase, server  : Authentification
activate user
user -> edit : clique sur le bouton "Activer les notifications"
activate edit
edit -> push : register()
activate push
push -> firebase : register()
activate firebase
firebase --> push : registerResponse
deactivate firebase
alt "succès"
push -> server : register()
activate server
server --> push : registerResponse
deactivate server
push --> edit  
edit --> user 
else "echec"
push --> edit  
deactivate push
edit --> user 
deactivate edit
end


deactivate user