@startuml sequence_lister_notification

hide footbox


actor "Utilisateur" as user
participant "NotificationsPage" as notifV << View >>
participant "notificationStore" as notif << ViewModel >>
participant "Notification" as notifM << Model >>

ref over user , notifV, notifM : authentification
ref over user , notifV, notifM : register
activate user
user -> notifV : glisse la notification vers la gauche
activate notifV
notifV -> notif : deleteNotification()
activate notif 
notif -> notifM : deleteNotification()
activate notifM
notifM --> notif : notifications
deactivate notifM 
notif --> notifV
deactivate notif
notifV --> user
deactivate notifV
deactivate user