@startuml sequence_simple_login

hide footbox


actor "Utilisateur" as user
participant "serverPage" as serView << View >>
participant "authStore" as auth << ViewModel >>
participant "Session" as session << Model >>
participant "EliseWebService" as ws << Service >>
activate user
user -> serView : saisie le serveur
activate serView
serView -> auth : submitForm()
activate auth
auth -> ws : setServerUrl()
activate ws
ws -> ws : IsAvailable()
alt server is available
    ws --> auth : server is available
    deactivate ws
    auth -> session : setServerUrl()
    activate session
    session --> auth : server stored
    deactivate session
    auth --> serView : server is available
    deactivate auth
    serView --> user : show Login form
    user -> serView : saisie identifiant/password
    serView -> auth : submitForm()
    activate auth
    auth -> ws : login()
    activate ws
    ws -> ws : UserIsAvailable()
    alt user is available
        ws --> auth : user is available
        auth -> session : extractSession()
        activate session
        session --> auth : session stored
        deactivate session
        auth --> serView : user is available
        deactivate auth
        serView --> user : affiche le message "bienvenue"
    else user is not available
        ws --> auth : user is not available
        activate auth
        auth --> serView : user is not available
        deactivate auth
        serView --> user : show error message
    end
else server is not available
    ws --> auth : server is not available
    deactivate ws
    activate auth
    auth --> serView : server is not available
    deactivate auth
    serView --> user : show error message
end
deactivate serView
deactivate user