@startuml sequence_logout

hide footbox


actor "Utilisateur" as user
participant "settingsPage" as setView << View >>
participant "authStore" as auth << ViewModel >>
participant "localStorage" as localStorage << Model >>

user -> setView : clique sur le bouton "déconnecter"
activate user
activate setView
setView -> auth : logout()
activate auth
auth -> localStorage : logout()
activate localStorage
localStorage -> localStorage : removeSession()
localStorage --> auth : user logged out
deactivate localStorage
auth --> setView : user logged out
deactivate auth
setView --> user : affiche le message "vous êtes déconnecté"


