@startuml sequence_logout

hide footbox


actor "Utilisateur" as user
participant "settingsPage" as setView << View >>
participant "authStore" as auth << ViewModel >>
participant "Session" as session << Model >>
ref over user, setView, auth, session : Authentification
user -> setView : clique sur le bouton "déconnecter"
activate user
activate setView
setView -> auth : logout()
activate auth
auth -> session : clearAll()
activate session
session --> auth
deactivate session
auth --> setView : user logged out
deactivate auth
setView --> user : affiche le message "vous êtes déconnecté"
deactivate setView
deactivate user

