@startuml refresh_data

hide footbox


actor "Utilisateur" as user
participant "système" as system


ref over user, system : Authentification
ref over user, system : Cas d'utilisation avec rafraichissement possible
activate user
user -> system : glisse son doigt vers le bas sur l'écran
activate system
system -> user : affiche les dernières données
deactivate system
deactivate user