@startuml sequence_refresh_data

hide footbox


actor "Utilisateur" as user
participant "PageActuelle" as page << View >>
participant "PageStore" as store << ViewModel >>
participant "Model" as model << Model >>
participant "EliseWebService" as service << Service >>

ref over user, page,store,model,service : Authentification
ref over user, page,store,model,service : Cas d'utilisation avec rafraichissement possible
activate user
user -> page : handleRefresh()
activate page
page -> store : refresh()
activate store
store -> service : GetModelData()
activate service
service -> store : ModelData
deactivate service
store -> model : update()
activate model
model --> store
deactivate model
store --> page
deactivate store
page -> user : actualiser les données 
deactivate user