@startuml download
hide footbox


actor "Utilisateur" as user
participant "système" as system


ref over user, system : Authentification
activate user
user -> system : clique sur le bouton "liste des action"
activate system
system --> user : affiche la liste des actions
user -> system : clique sur le bouton "télécharger le document"
alt Le système n'a pas le droit de télécharger
    system --> user : affiche un message d'erreur
else Le système a le droit de télécharger
    system -> system : télécharge les fichiers du document
alt document téléchargé
    system --> user : affiche le message "document téléchargé"
else document non téléchargé
    system --> user : affiche le message "une erreur lors du téléchargement du document"
end
end
deactivate system
deactivate user