@startuml sequence_favoris

hide footbox


actor "Utilisateur" as user
participant "FavoritesPage" as docView << View >>
participant "DocumentsStore" as documentVm << ViewModel >>
participant "Document" as documentM << Model >>
participant "EliseWebService" as ws << Service >>



ref over user, docView,docView,documentVm,documentM,ws : Authentification
activate user
user -> docView : Demande l'interface des favoris
activate docView
docView -> documentVm : getFavoriteDocuments()
activate documentVm
documentVm -> ws: GetFavoriteDocuments()
activate ws
ws -> documentVm: GetFavoriteDocumentsResponse
deactivate ws
documentVm -> documentM: setdocuments()
activate documentM
documentM --> documentVm
deactivate documentM
documentVm --> docView
deactivate documentVm
alt l'utilisateur a des favoris
    docView -> user : affiche les documents
else l'utilisateur n'a pas de favoris
    docView -> user : affiche le message "Vous n'avez pas de favoris"
end
deactivate user