@startuml sequence_download_file

hide footbox


actor "Utilisateur" as user
participant "PreviewFile" as fileView << View >>
participant "documentStore" as docVm << ViewModel >>
participant "File" as fileM << Model >>
participant "Filesystem" as fs << System >>



ref over user, fileView, docVm, fileM, fs : Authentification
activate user
user -> fileView : cliqueListeActions()
activate fileView
fileView -> user : affiche la liste des actions
user -> fileView : cliqueDownloadFile()
fileView -> fileM : getFile()
activate  fileM
fileM --> fileView : file
deactivate fileM
fileView -> docVm : downloadFile()
activate docVm
docVm -> fs : writeFile()
activate fs
alt fichier téléchargé
        fs --> docVm : fichier téléchargé
        docVm -> fileView : affiche le fichier téléchargé
    else fichier non téléchargé
        fs --> docVm : fichier non téléchargé
        deactivate fs
        docVm --> fileView : fichier non téléchargé
        deactivate docVm
end
fileView --> user : affiche le message

deactivate fileView
deactivate user