@startuml sequence_preview_files

hide footbox


actor "Utilisateur" as user
participant "DocumentPage" as docView << View >>
participant "DocumentContentPage" as fileView << View >>
participant "DocumentsStore" as documentVm << ViewModel >>
participant "Document" as documentM << Model >>



ref over user, docView,fileView,documentVm,documentM : Authentification
activate user
user -> docView : CliqueFichier()
activate docView
docView -> fileView : afficher les fichiers
deactivate docView
activate fileView
fileView -> documentVm : getDocumentFiles()
activate documentVm
documentVm -> documentM: getFiles()
activate documentM
documentM --> documentVm
deactivate documentM
documentVm --> fileView
deactivate documentVm
alt le document a des fichiers
    fileView -> user : affiche les fichiers
else le document n'a pas des fichiers
    fileView -> user : affiche le message "vous n'avez pas des fichiers"
end
deactivate user