@startuml sequence_traiter_task

hide footbox


actor "Utilisateur" as user
participant "TâchesDocument" as tasksDocument << View >>
participant "Tâches" as taskVm << ViewModel >>
participant "Tâche" as taskM << Model >>
participant "EliseWebService" as ws << Service >>


ref over user, tasksDocument,taskVm,taskM,ws : Authentification
activate user
user -> tasksDocument : CliqueTraiter()
activate tasksDocument
tasksDocument -> user : afficher le panneau de traitement
user -> tasksDocument : remplir le formulaire
user -> tasksDocument: choisir de confirmer ou d'annuler
alt confirmer
tasksDocument -> tasksDocument : valider le formulaire
alt formulaire valide
tasksDocument -> taskVm : changeTaskStatus()
activate taskVm
taskVm -> ws : ProcessTask()
activate ws
ws -> taskVm : ProcessTaskResponse
deactivate ws
taskVm -> taskM : UpdateTask()
activate taskM
taskM --> taskVm 
deactivate taskM
taskVm --> tasksDocument 
deactivate taskVm
alt action avec succès
  tasksDocument -> user : afficher un message de succès
else action échouée
  tasksDocument -> user : afficher un message d'erreur
end
else formulaire invalide
  tasksDocument -> user : afficher un message d'erreur
end

else annuler
  tasksDocument -> user : afficher un message d'annulation
end

tasksDocument -> tasksDocument : Refresh()
tasksDocument -> taskVm : getDocumentTasks()
activate taskVm
taskVm -> ws : GetTodoTasks()
activate ws
ws -> taskVm : GetTodoTasks
deactivate ws
taskVm -> taskM : GetTodoTasks()
activate taskM
taskM -> taskVm : GetTodoTasks
deactivate taskM
taskVm -> tasksDocument : getDocumentTasks
deactivate taskVm
tasksDocument -> user : afficher les tâches
deactivate tasksDocument
deactivate user