@startuml transfer_task

hide footbox


actor "Utilisateur" as user
participant "système" as system


ref over user, system : Authentification
activate user
user -> system : Clique sur le bouton "Transférer"
activate system
system -> user : Affiche l'interface de transfert
user -> system : remplit les champs
user -> system : Choisir de confirmer ou d'annuler le transfert
alt confirmer
system -> system : Transferer la tâche
alt transfert réussi
  system -> user : Affiche un message de confirmation
else transfert échoué
  system -> user : Affiche un message d'erreur
end
else annuler
system -> user : Affiche un message d'annulation
end
system -> user : Cache l'interface de transfert
deactivate system
deactivate user